#개발DB서버    
#spring:
#  datasource:
#    url: jdbc:log4jdbc:mysql://218.50.154.99:13306/refining_process?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&serverTimezone=Asia/Seoul
#    username: refining
#    password: 1234
#    driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://121.171.104.203:3306/test?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&serverTimezone=Asia/Seoul
    username: test
    password: 1234
    driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy